# Generated by Django 4.2.7 on 2025-03-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mapapi', '0006_discussionmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='Collaboration',
            name='motivation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='Collaboration',
            name='other_option',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='Collaboration',
            name='status',
            field=models.CharField(max_length=20, default='pending'),
        ),
    ]
