# Generated by Django 4.2.7 on 2025-07-17 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mapapi', '0010_organisationtag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('subdomain', models.CharField(max_length=255, unique=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('primary_color', models.CharField(default='#4CAF50', max_length=7)),
                ('secondary_color', models.CharField(default='#8BC34A', max_length=7)),
                ('background_color', models.CharField(default='#F0F0F0', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='evenement',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='events/'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='events/'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='incidents/'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='incidents/'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='incidents/'),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='zones/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='Mapapi.organisation'),
        ),
    ]
