# Generated by Django 4.2.7 on 2025-08-13 15:42

import backend.supabase_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mapapi', '0011_organisation_alter_evenement_audio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='audio',
            field=models.FileField(blank=True, null=True, storage=backend.supabase_storage.VoiceStorage(), upload_to='events/'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=backend.supabase_storage.ImageStorage(), upload_to='events/'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='video',
            field=models.FileField(blank=True, null=True, storage=backend.supabase_storage.VideoStorage(), upload_to='events/'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='audio',
            field=models.FileField(blank=True, null=True, storage=backend.supabase_storage.VoiceStorage(), upload_to='incidents/'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=backend.supabase_storage.ImageStorage(), upload_to='incidents/'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='video',
            field=models.FileField(blank=True, null=True, storage=backend.supabase_storage.VideoStorage(), upload_to='incidents/'),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='file',
            field=models.FileField(blank=True, null=True, storage=backend.supabase_storage.ImageStorage(), upload_to='reports/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.png', null=True, storage=backend.supabase_storage.ImageStorage(), upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='organisation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='organisation'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=backend.supabase_storage.ImageStorage(), upload_to='zones/'),
        ),
    ]
