# Generated by Django 4.2.7 on 2026-05-18 14:12

import backend.supabase_storage
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Mapapi', '0016_incident_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text="Si True, l'incident a été supprimé (corbeille)."),
        ),
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text="Si True, l'utilisateur a été supprimé (corbeille)."),
        ),
        migrations.CreateModel(
            name='FieldReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_lat', models.CharField(blank=True, help_text="Latitude réelle de l'agent lors du déplacement.", max_length=250, null=True)),
                ('location_lon', models.CharField(blank=True, help_text="Longitude réelle de l'agent lors du déplacement.", max_length=250, null=True)),
                ('distance_meters', models.FloatField(blank=True, help_text="Distance estimée entre l'agent et le lieu de l'incident (m).", null=True)),
                ('notes', models.TextField(blank=True, help_text="Observations de l'agent sur l'état des lieux.", max_length=1000, null=True)),
                ('photo', models.ImageField(blank=True, null=True, storage=backend.supabase_storage.ImageStorage(), upload_to='field_reports/')),
                ('visited_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date et heure du déplacement.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_reports', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_reports', to='Mapapi.incident')),
            ],
            options={
                'ordering': ('-visited_at',),
            },
        ),
    ]
