# Generated by Django 4.2.7 on 2026-06-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mapapi', '0023_organisation_logo_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidenttask',
            name='is_confirmed',
            field=models.BooleanField(default=False, help_text='True si la tâche a été confirmée par le leader. Seules les tâches confirmées comptent dans la progression.'),
        ),
    ]
