# Generated by Django 4.2.7 on 2026-06-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mapapi', '0025_incident_take_in_charge_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaboration',
            name='role',
            field=models.CharField(choices=[('leader', 'leader'), ('contributor', 'contributor'), ('observer', 'observer')], db_index=True, default='contributor', help_text="Rôle de l'organisation sur l'incident : leader, contributor ou observer.", max_length=20),
        ),
        migrations.AlterField(
            model_name='collaboration',
            name='status',
            field=models.CharField(db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='incident',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='etat',
            field=models.CharField(choices=[('declared', 'declared'), ('resolved', 'resolved'), ('in_progress', 'in_progress'), ('taken_into_account', 'taken_into_account')], db_index=True, default='declared', max_length=255),
        ),
        migrations.AlterField(
            model_name='incident',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text="Si True, l'incident a été supprimé (corbeille)."),
        ),
        migrations.AlterField(
            model_name='incident',
            name='is_public',
            field=models.BooleanField(db_index=True, default=True, help_text="Si False, l'incident n'est visible que par l'organisation de l'agent."),
        ),
        migrations.AlterField(
            model_name='incident',
            name='take_in_charge_mode',
            field=models.CharField(blank=True, choices=[('internal', 'Interne (organisation seule)'), ('collaborative', 'Collaborative (ouvert aux autres organisations)')], db_index=True, help_text='Mode de prise en charge choisi par la première organisation.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='incidenttask',
            name='is_confirmed',
            field=models.BooleanField(db_index=True, default=False, help_text='True si la tâche a été confirmée par le leader. Seules les tâches confirmées comptent dans la progression.'),
        ),
        migrations.AlterField(
            model_name='incidenttask',
            name='state',
            field=models.CharField(choices=[('pending', 'pending'), ('in_progress', 'in_progress'), ('done', 'done'), ('failed', 'failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='intervention_country',
            field=models.CharField(blank=True, choices=[('mali', 'Mali'), ('senegal', 'Sénégal'), ('guinea', 'Guinée'), ('burkina_faso', 'Burkina Faso'), ('niger', 'Niger'), ('cote_divoire', 'Côte d’Ivoire'), ('mauritania', 'Mauritanie')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('completed_with_warning', 'Completed with warning'), ('failed', 'Failed')], db_index=True, default='pending', max_length=32),
        ),
    ]
